version: '3.4'

services:
  wint-ui:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        - NODE_ENV=production
    command: npm start
    ports:
        - 3000:3000
    volumes:
        - .:/wint_ui